# Converts misaki EN lexicons (us/gb gold+silver JSON) into pre-grown TSV.gz embedded resources for KokoroSharp.
#
# Output format (UTF-8, '\n' newlines, inside .gz):
#   lines starting with '#'  -> comments/headers
#   '##GOLD' / '##SILVER'    -> section markers (gold = rating 4, silver = rating 3)
#   simple entry:  word<TAB>phonemes
#   tagged entry:  word<TAB>TAG=ps<TAB>TAG=ps...   ('TAG=' with empty ps encodes null; DEFAULT always present)
# Disambiguation rule for parsers: 2 columns and no '=' in column 1 => simple string entry, else tagged.
# ('=' never appears in any phoneme string or tag name; asserted below.)
#
# IMPORTANT: entries are already grown (misaki Lexicon.grow_dictionary applied at generation time),
# so the C# Lexicon must NOT re-grow capitalization variants at load.
import gzip, hashlib, io, json, os, random, sys

MISAKI = r'C:\Users\lyrco\source\_repos\KokoroSharpBinaries\models_notpushed\misaki'
OUT = r'C:\Users\lyrco\source\repos\MisakiSharp\data'
PARITY = r'C:\Users\lyrco\source\_repos\KokoroSharpBinaries\models_notpushed\parity'
DATA = os.path.join(MISAKI, 'misaki', 'data')
sys.path.insert(0, MISAKI)
from misaki.en import Lexicon  # heavy import (torch), but guarantees the exact grow logic

def encode_entry(k, v):
    assert k and '\t' not in k and '\n' not in k and not k.startswith('#'), repr(k)
    if isinstance(v, str):
        assert v and '\t' not in v and '\n' not in v and '=' not in v, repr(v)
        return f'{k}\t{v}'
    assert 'DEFAULT' in v, v
    cols = []
    for t, ps in sorted(v.items()):
        assert t and '=' not in t and '\t' not in t, repr(t)
        assert ps is None or (ps and '\t' not in ps and '\n' not in ps and '=' not in ps), repr(ps)
        cols.append(f'{t}={"" if ps is None else ps}')
    return k + '\t' + '\t'.join(cols)

def decode_entry(line):
    k, *cols = line.split('\t')
    if len(cols) == 1 and '=' not in cols[0]:
        return k, cols[0]
    return k, {t: (ps if ps else None) for t, ps in (c.split('=', 1) for c in cols)}

def build(lang):
    sections, raw_counts = {}, {}
    for section in ('gold', 'silver'):
        with open(os.path.join(DATA, f'{lang}_{section}.json'), encoding='utf-8') as r:
            raw = json.load(r)
        raw_counts[section] = len(raw)
        sections[section] = Lexicon.grow_dictionary(raw)
    return sections, raw_counts

def serialize(lang, sections, grown=True):
    buf = io.StringIO()
    buf.write(f'# misaki 0.9.4 {lang} lexicon, pre-grown={grown}, generated by generate_en_dict.py\n')
    for section, d in sections.items():
        buf.write(f'##{section.upper()}\n')
        for k in sorted(d):
            buf.write(encode_entry(k, d[k]) + '\n')
    return buf.getvalue().encode('utf-8')

def gz(data):
    buf = io.BytesIO()
    with gzip.GzipFile(fileobj=buf, mode='wb', mtime=0) as f:
        f.write(data)
    return buf.getvalue()

def verify_roundtrip(path, sections):
    with gzip.open(path, 'rt', encoding='utf-8', newline='\n') as f:
        parsed, current = {}, None
        for line in f:
            line = line.rstrip('\n')
            if line.startswith('##'):
                current = parsed.setdefault(line[2:].lower(), {})
            elif line and not line.startswith('#'):
                k, v = decode_entry(line)
                current[k] = v
    assert parsed.keys() == sections.keys()
    mismatches = sum(1 for s in sections for k in sections[s] if parsed[s].get(k) != sections[s][k])
    total = sum(len(d) for d in sections.values())
    assert all(len(parsed[s]) == len(sections[s]) for s in sections)
    return total, mismatches

os.makedirs(PARITY, exist_ok=True)
rng = random.Random(42)
fixture_lines = [
    '# Oracle lexicon fixtures: exact grown-dictionary entries + full-section SHA256, generated by generate_en_dict.py',
    '# H<TAB>lang<TAB>section<TAB>entryCount<TAB>sha256(  over "\\n".join(sorted(encoded lines)), UTF-8  )',
    '# S<TAB>lang<TAB>section<TAB>encodedEntryLine  (sampled; C# must reproduce the exact encoded form)',
]
report = {}
for lang in ('us', 'gb'):
    sections, raw_counts = build(lang)
    data = serialize(lang, sections)
    gz_bytes = gz(data)
    flat_bytes = len(gz(serialize(lang, {s: dict(json.load(open(os.path.join(DATA, f'{lang}_{s}.json'), encoding='utf-8'))) for s in sections}, grown=False)))
    path = os.path.join(OUT, f'en_lexicon_{lang}.tsv.gz')
    with open(path, 'wb') as f:
        f.write(gz_bytes)
    total, mismatches = verify_roundtrip(path, sections)
    for section, d in sections.items():
        lines = sorted(encode_entry(k, v) for k, v in d.items())
        sha = hashlib.sha256('\n'.join(lines).encode('utf-8')).hexdigest()
        fixture_lines.append(f'H\t{lang}\t{section}\t{len(lines)}\t{sha}')
        for line in rng.sample(lines, 1500):
            fixture_lines.append(f'S\t{lang}\t{section}\t{line}')
    report[lang] = dict(
        raw=raw_counts, grown={s: len(d) for s, d in sections.items()},
        raw_bytes=len(data), gz_bytes=len(gz_bytes), ungrown_gz_bytes=flat_bytes,
        roundtrip_total=total, roundtrip_mismatches=mismatches, path=path)

with open(os.path.join(PARITY, 'en_lexicon_fixtures.tsv'), 'w', encoding='utf-8', newline='\n') as f:
    f.write('\n'.join(fixture_lines) + '\n')
print(json.dumps(report, indent=2))
